#!/bin/sh
[ -d "$1" ] || exit
d="$(dirname "$1")"
b="$(basename "$1")"

# delete build files
rm -rf build/"$b"
rm -rf "$1"

# remove submodule extras
case "$d" in
    aur|my-aur)
	git config --remove-section submodule."$1"
	git config -f .gitmodules --remove-section submodule."$1"
	rm -rf .git/modules/"$1"
	;;
esac

for repo in packages/*.db; do
    if repo="$(readlink -e "$repo")"; then
	repo-remove "$repo" "$b" # remove the package from the repo
    fi
done

# update the remote about the removal
read -r url < global-url
rsync -lr --delete packages/ "$url"
