#!/bin/sh
[ "$1" ] || exit

. ./upload
for repo in build/repo/*.db; do
    if [ -e "$repo" ]; then
	repo-remove "$repo" "$(basename "$1")"
    fi
done
rsync -lr --delete build/repo/ $url

case "$(dirname "$1")" in
    aur|my-aur)
	git submodule deinit "$1"
	git rm -f "$1"
	;;
    *)
	rm -rf "$1"
	;;
esac
