#!/bin/sh
export FIX_BUILD_IN_USE=t

[ "$1" ] || exit
export BUILDDIR="$PWD"/build/build/"$1"
export PKGDEST="$PWD"/build/repo
export SRCDEST="$PWD"/build/src/"$1"
mkdir -p "$BUILDDIR" "$PKGDEST" "$SRCDEST"
for pkg in build/repo/"$1"-*.pkg.tar*; do
    [ -e "$pkg" ] && ln -srf "$pkg" "$1"
done
cd "$1" || exit
shift
if [ $# = 0 ]; then
    set -- bash
fi
"$@"
