#!/bin/sh
[ -d "$1" ] || exit
#d="$(dirname "$1")"
b="$(basename "$1")"

# setup build directories
export BUILDDIR="$PWD"/build
export PKGDEST="$PWD"/packages
export SRCDEST="$PWD"/build/"$b"
mkdir -p "$BUILDDIR" "$PKGDEST" "$SRCDEST"

# symlink already built packages so we don't rebuild ones downloaded
# by ./sync
for pkg in packages/"$b"-*.pkg.tar*; do
    [ -e "$pkg" ] && ln -srf "$pkg" "$1"
    find -L "$1" -type l -delete # delete broken symlinks
done

# apply changes in the edits/ directory to the build files
[ ! -f edits/"$b" ] || sed -i -f edits/"$b" "$1"/PKGBUILD

# change directories and run either a shell or whatever command was
# specified in the rest of the args
cd "$1" || exit; shift
[ $# != 0 ] || set -- "${SHELL:-sh}"
exec "$@"
