#!/bin/sh
for d
do
    if [ -d "$d" ]
    then
	git subtree pull -P "$d" https://aur.archlinux.org/"$d" HEAD
    else
	git subtree add -P "$d" https://aur.archlinux.org/"$d" HEAD
    fi
    ( cd "$d" && makepkg -crs )
    repo-add aurion.db.tar.xz "$d"/*.pkg.tar*
    mv "$d"/*.pkg.tar* .
done
