#!/bin/sh
mkdir -p build src
parallel 'mkdir -p src/{}' ::: "$@"
parallel 'cd {} && PKGDEST=../../build SRCDEST=../../src/{} makepkg -crs' ::: "$@"
repo-add -d build/aurion.db.tar.xz build/*.pkg.tar*
