#!/bin/sh
if [ ! "$FIX_PACKAGE_NAME" ]; then
    exec ./fix-build "$1" "$PWD"/rebuild "$@"
fi
case "$(dirname "$1")" in
    my-aur)
	updpkgsums
	makepkg --printsrcinfo > .SRCINFO

	makepkg -s

	git add -u
	git commit -m "Update $(basename "$1")"
	;;
    *)
	makepkg -s
	;;
esac
