#!/bin/sh
scndarg=already-recursed
[ -d "$1" ] || exit
[ "$2" = $scndarg ] || exec ./fix-build "$1" "$PWD"/rebuild "$1" $scndarg
d="$(dirname "$1")"
b="$(basename "$1")"
makepkg -s
if [ "$d" = my-aur ]; then
    updpkgsums
    makepkg --printsrcinfo > .SRCINFO
    makepkg -s
    git add -u
    git commit -m "Update $b"
fi
