#!/bin/sh
case "$(dirname "$1")" in
    my-aur)
	./rebuild "$1"
	git -C "$1" add -u
	git -C "$1" commit -m "Update $(basename "$1")"
	git -C "$1" push ssh://aur@aur.archlinux.org/"$(basename "$1")" master
	./pull "$1"
	;;
esac
