#!/bin/sh
url=root@zeus:/srv/http/aurion	# configure this

dir=build/repo
mkdir -p $dir
rsync -lru "$url"/ $dir
for repo in $dir/*.db; do
    repo="$(readlink -f "$repo")" && repo-add -n -R "$repo"  $dir/*.pkg.tar*
done
rsync -lr --delete $dir/ "$url"
